#pragma checksum "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8ce516e18b4b3d1194e4af7a4522dc3390fabf09614cf3be1b4ea0ef9b54909c"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Product_ProductList), @"mvc.1.0.view", @"/Views/Product/ProductList.cshtml")]
namespace AspNetCore
{
    #line hidden
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Mvc;
    using global::Microsoft.AspNetCore.Mvc.Rendering;
    using global::Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\_ViewImports.cshtml"
using StokTakip2023;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\_ViewImports.cshtml"
using StokTakip2023.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\_ViewImports.cshtml"
using EntityLayer.Concrete;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\_ViewImports.cshtml"
using BusinessLayer.Abstract;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"8ce516e18b4b3d1194e4af7a4522dc3390fabf09614cf3be1b4ea0ef9b54909c", @"/Views/Product/ProductList.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA256", @"97cc8ab97bf729af10d6c3b153a8d6176f672827772e3be0c03f9becb1b45be3", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Product_ProductList : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<Product>>
    #nullable disable
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
  
    ViewData["Title"] = "ProductList";
    Layout = "~/Views/Shared/_Layout.cshtml";

#line default
#line hidden
#nullable disable
#nullable restore
#line 6 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
 if (this.User.IsInRole("Admin"))
{

#line default
#line hidden
#nullable disable
            WriteLiteral("    <a class=\"btn btn-success\" href=\"/Product/Create/\">+ Yeni Ürün</a>\r\n");
#nullable restore
#line 9 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
}

#line default
#line hidden
#nullable disable
            WriteLiteral("    <table id=\"productTable\" class=\"table table-striped table-bordered\">\r\n        <thead>\r\n            <tr>\r\n                <th>#</th>\r\n                <th>Ürün Adı</th>\r\n                <th>Stok Miktarı</th>\r\n");
#nullable restore
#line 16 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                 if (this.User.IsInRole("Admin"))
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <th>Düzenle</th>\r\n                    <th>Sil</th>\r\n");
#nullable restore
#line 20 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <th>Zimmet Talebi</th>\r\n");
#nullable restore
#line 24 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("            </tr>\r\n        </thead>\r\n        <tbody>\r\n");
#nullable restore
#line 28 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
             foreach (var product in Model)
            {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <tr>\r\n                <td>");
#nullable restore
#line 31 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
               Write(product.ProductID);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 32 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
               Write(product.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                <td>");
#nullable restore
#line 33 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
               Write(product.UnitsInStock);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n");
#nullable restore
#line 34 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                 if (this.User.IsInRole("Admin"))
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <td><a class=\"btn btn-info\"");
            BeginWriteAttribute("href", " href=\"", 1094, "\"", 1133, 2);
            WriteAttributeValue("", 1101, "/Product/Edit/", 1101, 14, true);
#nullable restore
#line 36 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
WriteAttributeValue("", 1115, product.ProductID, 1115, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Düzenle</a></td>\r\n                    <td><a class=\"btn btn-danger\"");
            BeginWriteAttribute("href", " href=\"", 1202, "\"", 1243, 2);
            WriteAttributeValue("", 1209, "/Product/Delete/", 1209, 16, true);
#nullable restore
#line 37 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
WriteAttributeValue("", 1225, product.ProductID, 1225, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Sil</a></td>\r\n");
#nullable restore
#line 38 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                }
                else
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <td><a class=\"btn btn-warning\"");
            BeginWriteAttribute("href", " href=\"", 1369, "\"", 1415, 2);
            WriteAttributeValue("", 1376, "/Assign/CreateAssign/", 1376, 21, true);
#nullable restore
#line 41 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
WriteAttributeValue("", 1397, product.ProductID, 1397, 18, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(">Zimmet Talebi+</a></td>\r\n");
#nullable restore
#line 42 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("            </tr>\r\n");
#nullable restore
#line 44 "C:\Users\ruzbi\OneDrive\Masaüstü\StokTakip2023\StokTakip2023\Views\Product\ProductList.cshtml"
            }

#line default
#line hidden
#nullable disable
            WriteLiteral("        </tbody>\r\n    </table>\r\n\r\n\r\n\r\n\r\n\r\n");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<Product>> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
